name: AutoMinifyJS
on:
  push:
    branches: [ master ]
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Minify
        uses: nizarmah/auto-minify@v1.8
        with:
          directory: src/frontend
          maxdepth: 1
