name: AutoMinifyJS
on:
  push:
    branches: [ master ]
jobs:
  minify:
    runs-on: ubuntu-latest
    steps:
      - name: fuck you
        run: ls
        
      - name: Auto Minify
        uses: nizarmah/auto-minify@v1.8
        with:
          maxdepth: 1
          directory: "CursorMess/src/frontend"
      
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}
          repository: "CursorMess'"
